/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/Chart/index.vue')['default']
    DragList: typeof import('./src/components/DragList/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HighLevelCalculator: typeof import('./src/components/HighLevelCalculator/index.vue')['default']
    HomePage: typeof import('./src/components/HomePage/index.vue')['default']
    LongList: typeof import('./src/components/List/LongList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanList: typeof import('vant/es')['List']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
  }
}
